// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqzyixyvgepgbkkewohw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxenlpeHl2Z2VwZ2Jra2V3b2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDg5NzMsImV4cCI6MjA2NzYyNDk3M30.AL-tPbFg1wJXtCS2PKetURfexvnf-Dptl4t9aUyJ0Qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});